# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 06:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('Chapter_Name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('Chapter_Created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='outreach_permision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permision_Type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('Region_Name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('Region_Created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Chapter')),
                ('Mentor_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.outreach_permision')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='Chapter_Regoin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Region'),
        ),
    ]
