# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.Region'),
            preserve_default=False,
        ),
    ]
