# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_userprofile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='User_Full_Name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='User_Phone_Number',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
