# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0005_auto_20160124_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='CRM_Record_ID',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
