# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 07:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='Mentee_Address',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Mentee_Child_Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=80),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Mentee_Child_T1D_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Mentee_Childs_Age',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Mentee_Diagnosis_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 1, 21, 7, 19, 44, 476000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentee',
            name='Mentee_Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Mentee_Hospital_Endo',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Mentee_Notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Mentee_Phone_Number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='mentee',
            name='Mentee_School_Grade',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
