# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0002_auto_20160120_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='Mentee_Updated_By',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='Mentee_Created_By',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
