# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0004_mentee_mentee_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Chapter',
            new_name='Chapter',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Child_Gender',
            new_name='Child_Gender',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Child_T1D_name',
            new_name='Child_T1D_name',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Childs_Age',
            new_name='Childs_Age',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Created_By',
            new_name='Created_By',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Diagnosis_Date',
            new_name='Diagnosis_Date',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Hospital_Endo',
            new_name='Hospital_Endo',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Notes',
            new_name='Notes',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Phone_Number',
            new_name='Phone_Number',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Region',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_School_Grade',
            new_name='School_Grade',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_Updated_By',
            new_name='Updated_By',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Mentee_updated',
            new_name='updated',
        ),
    ]
