# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 01:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0007_auto_20160125_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentee',
            old_name='Name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Hospital_Endo',
            new_name='Hospital',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='Address',
            new_name='Mailing_Address_Line_1',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='School_Grade',
            new_name='School',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='Childs_Age',
        ),
        migrations.AddField(
            model_name='mentee',
            name='Childs_DOB',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 3, 11, 1, 24, 58, 871000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
