# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0009_auto_20160310_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentee',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='mentee',
            old_name='LastName',
            new_name='Last_Name',
        ),
    ]
