# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='Log_Date',
            new_name='Activity_Date',
        ),
    ]
