# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20160126_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='Log_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.UserProfile'),
        ),
    ]
