# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20160125_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='Log_Mentee',
            new_name='Log_Outreach_Volunteer',
        ),
    ]
