# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20160125_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='Log_Outreach_Volunteer',
            new_name='Outreach_Family',
        ),
    ]
