# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20160125_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='Log_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.UserProfile'),
        ),
    ]
