# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20160126_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='JDRF_Resource_Sent',
            field=models.CharField(blank=True, choices=[('Bag of Hope', 'Bag of Hope'), ('Chapter Outreach activity/event information', 'Chapter Outreach activity/event information'), ('Experienced Adult Toolkit', 'Experienced Adult Toolkit'), ('Newly Diagnosed Adult Toolkit', 'Newly Diagnosed Adult Toolkit'), ('One Walk Kickoff Information/Invitation', 'One Walk Kickoff Information/Invitation'), ('One Walk information/Invitation', 'One Walk information/Invitation'), ('Pregnancy Toolkit', 'Pregnancy Toolkit'), ('School Advisory Toolkit', 'School Advisory Toolkit'), ('T1D Care Kit', 'T1D Care Kit'), ('Teen Toolkit', 'Teen Toolkit'), ('TrialNet Brochure', 'TrialNet Brochure'), ('TypeOneNation Summit Information/Invitation', 'TypeOneNation Summit Information/Invitation'), ('Other (in notes section provide details)', 'Other (in notes section provide details)')], max_length=80),
        ),
        migrations.AlterField(
            model_name='log',
            name='Log_Method',
            field=models.CharField(blank=True, choices=[('Phone call', 'Phone call'), ('E-Mail', 'E-Mail'), ('In-Person Meeting', 'In-Person Meeting'), ('Social Media', 'Social Media'), ('Text Message', 'Text Message'), ('USPS Mailing', 'USPS Mailing')], max_length=80),
        ),
    ]
